[build-system]
requires = ["briefcase>=0.3.0"]
build-backend = "briefcase.build"

[tool.briefcase]
project_name = "MyApp"
bundle = "com.example"
version = "0.1.0"
url = "https://example.com"
license = "MIT"
author = "Your Name"
author_email = "your@email.com"

[tool.briefcase.app.myapp]
formal_name = "MyApp"
description = "My Toga Application"
sources = ["src/myapp"]
icon = "resources/icon"

[tool.briefcase.app.myapp.android]
requires = [
    "toga-android>=0.3.0",
]