[build-system]
requires = ["briefcase"]
build-backend = "briefcase.backend"

[tool.briefcase]
project_name = "MyApp"
bundle = "org.example"
version = "0.1.0"
description = "My first Briefcase app"  # Обязательное поле
license = "MIT"                        # Обязательное поле
author = "Your Name"
author_email = "your@email.com"

[tool.briefcase.app.myapp]
formal_name = "MyApp"
sources = ["src/myapp"]