[build-system]
requires = ["briefcase>=0.3.23"]
build-backend = "briefcase.backend"

[tool.briefcase]
project_name = "MyApp"
bundle = "org.example"
version = "0.1.0"
description = "My Android App"
license = "MIT"
author = "Your Name"

[tool.briefcase.app.myapp]
formal_name = "MyApp"
sources = ["src/myapp"]