[tool.briefcase]
project_name = "MyApp"
bundle = "org.example.myapp"
version = "0.0.1"
url = "https://example.com"
license = "MIT"
author = "Your Name"
author_email = "you@example.com"

[tool.briefcase.app.myapp]
formal_name = "MyApp"
description = "Short Hello World"
sources = ["src/myapp"]
entry_point = "myapp:main"
requires = ["toga"]

[tool.briefcase.app.myapp.android]
permissions = []