name: Build Android APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android
          sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Build APK
        run: |
          python -m briefcase create android
          python -m briefcase build android
          python -m briefcase package android --no-sign

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: android/bin/*.apk
          retention-days: 7  # Автоматическое удаление через 7 дней (опционально)