name: Build Android APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android
          sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Build APK
        run: |
          # Создаем временную папку для сборки
          mkdir -p android_build
          cd android_build
          
          # Инициализируем проект Briefcase
          python -m briefcase new
          
          # Копируем ваши исходники
          cp -r ../src/* ./src/
          cp ../pyproject.toml .
          
          # Собираем APK
          python -m briefcase create android
          python -m briefcase build android
          python -m briefcase package android --adhoc
          
          # Сохраняем путь к APK
          APK_PATH=$(find . -name "*.apk" | head -1)
          echo "APK_PATH=${APK_PATH}" >> $GITHUB_ENV
          echo "APK найден по пути: ${APK_PATH}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ env.APK_PATH }}
          if-no-files-found: error