name: Build Android APK

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga-android
          sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/**') }}-v1
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: |
          rm -rf android/
          python -m briefcase create android
          python -m briefcase build android
          python -m briefcase package android --adhoc
          
          echo "Поиск APK файлов..."
          find . -name "*.apk" -exec ls -lh {} \;

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: |
            android/bin/**/*.apk
            android/app/build/outputs/apk/**/*.apk
            android/app/build/outputs/bundle/**/*.aab
            build/**/*.apk
          if-no-files-found: error
          retention-days: 7