name: Build Android APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toga[android]

      - name: Create Android project (if not exists)
        run: |
          if [ ! -d "build/hellotoga/android" ]; then
            briefcase create android
          fi

      - name: Build APK
        run: |
          briefcase build android

      - name: Package APK
        run: |
          briefcase package android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/hellotoga/android/gradle/app/build/outputs/apk/debug/app-debug.apk