name: Build Kivy Android App

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    # Основное кеширование
    - name: Cache Android SDK/NDK
      uses: actions/cache@v3
      id: cache-android
      with:
        path: |
          ~/.buildozer/android/platform
          ~/.android/cache
        key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Cache Gradle
      uses: actions/cache@v3
      id: cache-gradle
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Python
      uses: actions/cache@v3
      id: cache-python
      with:
        path: |
          ~/.cache/pip
          ~/.local/lib/python3.9/site-packages
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt', 'buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-python-

    # Установка только при отсутствии кеша
    - name: Install system dependencies
      if: steps.cache-android.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses-dev cmake libffi-dev libssl-dev \
          imagemagick

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python tools
      if: steps.cache-python.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython==0.29.32

    # Подготовка Gradle
    - name: Configure Gradle
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
        echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
        echo "android.useAndroidX=true" >> ~/.gradle/gradle.properties

    # Сборка с автоматическим повтором при ошибках
    - name: Build APK
      run: |
        for i in {1..3}; do
          buildozer -v android debug && break || sleep 10
        done

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 3