name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Кеширование зависимостей

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            libffi-dev \
            libssl-dev

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir briefcase==0.3.23 toga==0.3.0

      - name: Verify installation
        run: |
          python -c "import briefcase; print(f'Briefcase version: {briefcase.__version__}')"
          python -c "import toga; print(f'Toga version: {toga.__version__}')"

      - name: Build Android APK
        run: |
          mkdir -p src/myapp
          [ -f src/myapp/app.py ] || cat > src/myapp/app.py <<EOF
          import toga
          from toga.style import Pack
          def build(app):
              return toga.Box(children=[
                  toga.Label("Hello World!", style=Pack(padding=20))
              ])
          def main():
              return toga.App("MyApp", "org.example.myapp", startup=build)
          EOF
          
          briefcase create android
          briefcase build android
          briefcase package android --packaging-format apk --adhoc-sign

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/*.apk