name: Build APK with Kivy/Buildozer Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull compatible Docker image and run Buildozer
      run: |
        docker pull kivy/buildozer:python3
        docker run --rm -v ${{ github.workspace }}:/home/user/app \
          -w /home/user/app \
          kivy/buildozer:python3 \
          buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk