name: Build APK with Kivy/Buildozer Docker

on:
  push:           # Запуск при любом push
  pull_request:   # Запуск при любом Pull Request

jobs:
  build:
    runs-on: ubuntu-22.04
    container: kivy/buildozer  # Используем официальный Docker-контейнер

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install git (внутри контейнера часто отсутствует)
      run: apt update && apt install -y git

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk