name: Build Kivy APK

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev libssl-dev

      - name: Install Buildozer
        run: pip install buildozer cython==0.29.32

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK (v4)
        uses: actions/upload-artifact@v4  # Актуальная версия!
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 7