- name: Build APK
  run: |
    # Очистка предыдущих сборок
    rm -rf bin/ .buildozer/android/platform/build-*
    
    # Сборка с подробными логами
    buildozer -v android debug 2>&1 | tee build.log
    
    # Проверка APK
    APK_PATH=$(find . -path "./bin/*.apk" -o -path ".buildozer/android/platform/build-*/dists/*/bin/*.apk" -print -quit)
    if [ -z "$APK_PATH" ]; then
      echo "❌ APK не найден! Критические ошибки:"
      grep -i -E "error|fail" build.log
      exit 1
    else
      echo "✔ APK найден: $APK_PATH"
      # Копируем в стандартную папку bin/
      mkdir -p bin
      cp "$APK_PATH" bin/output.apk
    fi

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: app-debug
    path: bin/output.apk
    retention-days: 3