name: Build Kivy Android App

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Create default assets if missing
      run: |
        if [ ! -f icon.png ]; then
          convert -size 512x512 xc:white icon.png
        fi
        if [ ! -f presplash.png ]; then
          convert -size 1280x720 xc:black presplash.png
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses-dev cmake libffi-dev libssl-dev \
          imagemagick  # Для создания стандартных изображений

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Buildozer
      run: |
        pip install --upgrade pip wheel
        pip install buildozer cython==0.29.32

    - name: Build APK
      run: |
        buildozer -v android debug
        ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk