name: Build Kivy Android App

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Явно указываем версию Ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Update apt cache
      run: sudo apt-get update -qq

    - name: Install system dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses-dev cmake libffi-dev lib