name: Build Briefcase APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Briefcase
        run: pip install briefcase

      - name: Initialize Android project
        run: |
          briefcase create android

      - name: Build APK
        run: |
          briefcase build android

      - name: Package APK
        run: |
          briefcase package android --format apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-briefcase
          path: android/*.apk
          retention-days: 3